var e1=document.createElement('h1')
console.log(e1)
var e2=document.createElement('p')
console.log(e2)
var e3=document.createElement('h3')
console.log(e3)
var e4=document.createElement('p')
console.log(e4)
var e5=document.createElement('div')
console.log(e5)
var e6=document.createElement('div')
console.log(e6)
e5.appendChild(e1)
e5.appendChild(e2)
e6.appendChild(e3)
e6.appendChild(e4)
document.body.appendChild(e5)
document.body.appendChild(e6)